### ISSUE TITLE
Do you need an API Key from TDA to run?

### ISSUE THREAD

**Issue by anrivera16** [Smayxor/stock#3]
I might be an idiot but i cannot file the Color Module.

**Comment by Smayxor** [comment]
Hi, I'm currently switching the code over to use Tradier API in anticipation of Schwab merger.
stock.py is the old version which has a GUI, I dont remember it well.   currently using oauth.py discord only
 I think you can probably just fill the list on your own, it tries to build a ColorGradient between red and green
red = Color("#FF0000")
colorGradient = list(red.range_to(Color("#00FF00"),10))
colorGradient[0] = "#FF0000"
colorGradient[9] = "#00FF00"
perhaps could just say
for x in range(10): colorGradient[x] = "#00FF00"
As memory serves me the color gradient was for an old rating system I had on fundamentals.  As I recall the yahoo code stopped working

________________________________
From: anrivera16 ***@***.***>
Sent: Monday, October 23, 2023 5:48 PM
To: Smayxor/stock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Smayxor/stock] Having issues with Color Module (Issue #3)


I might be an idiot but i cannot file the Color Module.

**Comment by Smayxor** [comment]
Also its spelt  coloUr  must be a british module 🙂
pip3 install colour
________________________________
From: anrivera16 ***@***.***>
Sent: Monday, October 23, 2023 5:48 PM
To: Smayxor/stock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Smayxor/stock] Having issues with Color Module (Issue #3)


I might be an idiot but i cannot file the Color Module.

**Comment by Smayxor** [comment]
So currently the oauth.py is set to use Tradier API, which is significantly easier to get running than TDA.   I made a copy of that file for TDA.   I haven't had any confirmations the new Schwab API is running yet,  my account will be converted Nov 6th

**Comment by anrivera16** [comment]
Thanks for the updates @Smayxor . Still waiting for my account to switch over as well. When it does i would love to test it out with Tradier API.

**Comment by Smayxor** [comment]
Tradier is a completely different Broker.  No need to wait

**Comment by Smayxor** [comment]
I added a Tradier fork.  It has new files
datapuller.py   drawchart.py  and gexgui.py
You wont need discordbot.py,  but running gexgui.py is currently able to bring up a gex chart.  It's still being developed
